### PR TITLE
fix for sentry 20.12+ (python 3.6)

### PR DESCRIPTION
**Pull request by konstantin-leontev**
Tested on Sentry 20.12.1 (Python 3.6.10)

### CODE REVIEW

**Comment by butorov** [comment]
Thanks a lot @konstantin-leontev!
Do you have any capacity to add related test into existing test-suite?
Your changes seem working for the previous version too - https://travis-ci.org/github/butorov/sentry-telegram/builds/758241235

**Comment by omidraha** [comment]
Please merge

**Comment by Olegt0rr** [comment]
@butorov, please, don't make this repo abandoned

**Comment by omidraha** [comment]
There is an active [fork](https://github.com/vortland/sentry-telegram). version that is compatible with `Python 3.0+`  and `Sentry 20+`,
Also it's good idea to merge with this fork.

**Pull request merged**
